//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailProduct
    {
        public int id { get; set; }
        public Nullable<int> reviews_number { get; set; }
        public string availability { get; set; }
        public string shipping_day { get; set; }
        public string weight { get; set; }
        public string detail_description { get; set; }
        public string review_comment { get; set; }
        public string meta { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<int> order { get; set; }
        public Nullable<System.DateTime> datebegin { get; set; }
        public Nullable<int> productid { get; set; }
    }
}
